### ISSUE TITLE
Parallel Matrix Actions Fail When Connecting to Twingate

### ISSUE THREAD

**Issue by gal-terra** [Twingate/github-action#12]
I have a GitHub workflow that runs a matrix of actions to deploy services to EKS. Each action within the matrix connects to Twingate using the same service key and then attempts to run helm upgrade. However, only one service deployment succeeds at a time.

When I rerun the failed jobs using the Re-run failed jobs option, another action succeeds while the rest fail. I can repeat this process multiple times until the workflow is eventually completed successfully. This suggests that multiple connections to Twingate cannot be established in parallel.

I also attempted to connect to Twingate at the workflow level (before the matrix actions) to see if it would resolve the issue, but it didn't work.

Below is a simplified version of the workflow YAML to demonstrate the issue:

```
name: deploy-api
inputs:
  twingate-service-key:
    description: 'Twingate service key'
    required: true

runs:
  using: composite
  steps:
    - name: Configure Twingate
      uses: twingate/github-action@v1
      with:
        service-key: ${{ inputs.twingate-service-key }}

    - name: Deploy
      uses: koslib/helm-eks-action@master
      env:
        KUBE_CONFIG_DATA: ${{ env.KUBE_CONFIG_DATA }}
      with:
        command: |
          helm upgrade --install ${{ inputs.app-name }} ${{ inputs.deployment-chart }} \
          --namespace ${{ inputs.namespace }} \
          --values ${{ inputs.deployment-chart }}/values.yaml \
          --values ${{ inputs.app-values }} \
          --set version=${{ inputs.app-name }}-${{ inputs.image-tag }} \
          --set image=${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr-repository }} \
          --set environment=production \
          --atomic --timeout 5m
```
It appears that Twingate does not support multiple parallel connections with the same service key. If that’s the case, guidance on how to configure Twingate for parallel matrix jobs would be appreciated.

**Comment by ekampf** [comment]
You'll have to define multiple keys as secrets and refer to each key by the matrix value?

**Comment by ekampf** [comment]
Actually github has a nice way of supporting this:
You can define a matrix like this:
```
        matrix:
          runs-on: [ubuntu-latest, ubuntu-24.04, ubuntu-22.04, ubuntu-20.04]
          include:
            - runs-on: ubuntu-latest
              service_key: ${{ secrets.SERVICE_KEY1 }}
            - runs-on: ubuntu-24.04
              service_key: ${{ secrets.SERVICE_KEY2 }}
            - runs-on: ubuntu-22.04
              service_key: ${{ secrets.SERVICE_KEY3 }}
            - runs-on: ubuntu-20.04
              service_key: ${{ secrets.SERVICE_KEY4 }}
```

and then use:
```
- name: Configure Twingate
  uses: twingate/github-action@v1
  with:
     service-key: ${{ matrix.service_key }}
```
