### ISSUE TITLE
Add ability for a pool of service account keys to be used

### ISSUE THREAD

**Issue by agriffin208** [Twingate/github-action#33]
### Overview

Currently, the Twingate GitHub Action only allows specifying a single service account key for authentication. However, when multiple jobs run simultaneously using the same key, they may be throttled by the controller as the service account key is seen as a "single" client. To mitigate this, we can add the ability to provide a pool (array) of service account keys. The action should randomly select, or other selection methods if available, a key from the pool to distribute the load more effectively.

### Proposed Solution

Enable the GitHub Action to accept multiple service account keys as an input (e.g., via GitHub Secrets or another means). The action should then randomly select a key from the pool for each run to reduce throttling risks. Below is an example implementation provided by a customer using the GH action.
```
- name: Randomly select Twingate service key from pool
  run: echo "tg_key=$(jq -r -c '.[]' <<< '${{ secrets.TWINGATE_INFRA_SERVICE_KEYS }}' | shuf -n 1)" >> $GITHUB_ENV

- name: Connect to Twingate
  uses: twingate/github-action@4493ffc3806241aa98194a3fa679f874bce013b5 # V1.1
  with:
    service-key: ${{ env.tg_key }}
```
