### ISSUE TITLE
Twingate not-running

### ISSUE THREAD

**Issue by qxmips** [Twingate/github-action#7]
```
Setup is complete.
Starting Twingate service in headless mode
Twingate has been started
Waiting for status...
not-running
Exiting with error as TwinGate is not connected
Error: Process completed with exit code 1.
```

**Comment by Ethaan** [comment]
@qxmips did you fix this? i think this is because the way we pass the key

**Comment by scana** [comment]
Hi @ekampf, we're observing this error every now and then, preventing our builds from passing.
Usually re-running a job fixes the issue but sometimes it's just stuck for hours.

Our setup is basic:
```yaml
- name: Setup twingate
  uses: twingate/github-action@v1
  with:
    service-key: ${{ secrets.TWINGATE_TOKEN }}
```
